### PR TITLE
Close #6

### LINKED ISSUE #6: WGLC: Say how a receiver handles syntactically invalid application/multipart-core representations
Klaus:
> There should be a sub-section or paragraph specifying what a
> recipient of a application/multipart-core representation should do if
> it encounters something that doesn't match the grammar. Does the whole
> array become unusable when there is an unexpected element, or can a
> recipient use the array up to the unexpected element? Should a
> recipient try to do error recovery and skip to the next element? This
> has impact on how the format can be evolved in the future.

Carsten seems to prefer failing hard and early (draft-iab-protocol-maintenance).

Thomas loves simplicity and +1 Carsten's proposal.

### PR DESCRIPTION
**Pull request by cabo**

### CODE REVIEW

**Comment by ektrah** [comment]
So, a multipart representation can be processed up till the first error? Works for me.

**Comment by cabo** [comment]
I think we have to avoid saying "must check the whole thing before acting on any of it".  The intention was not to say "If there is an error, you have to process up to the error".  Is that what you read there?

**Comment by thomas-fossati** [comment]
> So, a multipart representation can be processed up till the first error? Works for me.

mmm, that's not how I interpret "stop processing".  Maybe "invalidate processing"?

**Comment by cabo** [comment]
But that is too close the meaning I'm trying to avoid.
Maybe we can leave it slightly open as it is proposed now?

**Comment by thomas-fossati** [comment]
> But that is too close the meaning I'm trying to avoid.

Sorry I'm not following: Which meaning are you trying to avoid?

> Maybe we can leave it slightly open as it is proposed now?

I think not removing the ambiguity in the text is a bad thing.

**Comment by thomas-fossati** [comment]
Nice, thanks.

**Comment by cabo** [comment]
Klaus still sees a problem with assigning too much leeway to the application in giving the positioning special semantics.  We'll need to discuss this a bit further...

**Comment by thomas-fossati** [comment]
> Klaus still sees a problem with assigning too much leeway to the application in giving the positioning special semantics. We'll need to discuss this a bit further...

I don't see how we could limit applications in this sense?  It's intrinsically a piece of malleable data.

**Comment by cabo** [comment]
Well, this is introductory material that tells readers how this is supposed to be used.  I made a proposal that I think reflects Klaus' sentiment.  In the process, I lost the part that needed the fix requested by #6, but I think that is OK -- an introduction should not really have a MUST anyway.

@ektrah — better?

**Comment by thomas-fossati** [comment]
Apart from the array, set and struct-like use cases, it'd be worth mentioning the "union" pattern?

**Comment by ektrah** [comment]
LGTM

**Comment by thomas-fossati** [comment]
@cabo do you want to re-integrate af472b3 here or prefer to merge as-is?

**Comment by cabo** [comment]
Since about 9 hours I'm trying to write the union sentence; crazy day.

**Comment by cabo** [comment]
And, yes, af472b3 should stay in, but I don't care in which PR :-)

**Comment by cabo** [comment]
If you like the wording of the union pattern, this can go in and we can submit the next version.

**Comment by thomas-fossati** [comment]
Go for it! FWIW I like it very much.

**Pull request merged**
